# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 123456
  

development:
  <<: *default
  database: sequra_fz_development

 
test:
  <<: *default
  database: sequra_fz_test

#
production:
  <<: *default
  database: sequra_fz_production
  username: sequra_fz
  password: <%= ENV["SEQURA_FZ_DATABASE_PASSWORD"] %>
